// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbgntercswdfvjopvgmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZ250ZXJjc3dkZnZqb3B2Z21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDI4MTEsImV4cCI6MjA2Mzc3ODgxMX0.ngpGSCMUPo0_KYQA7Febew3rbTcatFJeyubXqY6omAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);